### ISSUE TITLE
How to @reset when the field is known only by its equivalent symbol.

### ISSUE THREAD

**Issue by DavidSagan** [JuliaObjects/Accessors.jl#117]
Given something like:
> struct A; a; end
> z = A(1)
> b = \:a
I want to modify the `b` property (which is a symbol for the `a` field) of `z` using something like:
> @reset Base.getproperty(z,b) = 2
But this does not work. Is there any way to do what I want?
That is, I have a function where I am passed `z` and `b` so the function does not "know" to write `@reset z.a = 2`.

**Comment by jw3126** [comment]
Here is one way to do it:
```julia
julia> using Accessors

julia> z = (a=1,)
(a = 1,)

julia> b = :a
:a

julia> optic = PropertyLens(b)
(@optic _.a)

julia> @reset optic(z) = 2
(a = 2,)
```
