### ISSUE TITLE
Traversal order of `Recursive`

### ISSUE THREAD

**Issue by jariji** [JuliaObjects/Accessors.jl#143]
Are there any guarantees on the traversal order of `Recursive`?

**Comment by jariji** [comment]
> I think the only achievable order is determined by whatever the passed optic argument does. 

That sounds good. Do `Elements()` and `Properties()` have a defined order? 

> Do you have an example where there are several reasonably possible orders?

I feel this interface is related to Transducers which makes me think it's going to eventually become parallel so order is going to become indeterminate for code like this or similar.


```jl
julia> let i = 0
           modify((;a=10, b=20), @o _ |> Elements()) do x
               i += 1
           end
       end
(a = 1, b = 2)
```

**Comment by jw3126** [comment]
It is not documented, but I agree with what @aplavin said:
* I consider the order or even the number of calls to `f` an implementation detail. Would be good to document though.
* If we ever want to parallelize, that would be opt in, like it is in Transducers. At least in my use cases Accessors usually does such tiny computations that splitting them between threads etc would be slower.
And if parallel is opt in, we can impose whatever extra requirements we want about `f`.

**Comment by jariji** [comment]
> if you have some specific usecases in mind, that would benefit from well-defined traversal order

There are plenty of other ways to do this that don't rely on order, but here's a use case that came to mind. Optim.optimize wants an array, so one way to turn a struct into an array and back is 
- create an empty array `a`
- traverse through the struct of initial values, assigning `a[i] = x` and `modify`ing each value by replacing the struct value with `i += 1`
- optimize with `a`
- traverse over the struct again, and for `modify`ing each entry by replacing it with `a[i]` to put the minimizer for the `i`the parameter back into its right place in the struct.

That relies on the traversal going the same way both times.

> if you have some specific usecases in mind, that would benefit from ... parallelization

All the parallel monoid operations we often do on vectors are quite tree-shaped. Eg summing up the nodes in a tree, searching an XML/HTML/JSON tree for a pattern.

**Comment by jariji** [comment]
> The first (optimization) case is very convenient with getall + setall. 

Alright. getall/setall might want to document that they traverse in the same order as each other. 

> Oh, this is a weaker and totally reasonable guarantee to have (in sequential code) – to avoid any potential confusion. That is, "modify() can traverse in any order, but the order remains the same for multiple calls".

Good point. 

What happens if setall adds new nodes: which properties of the traversal order are preserved: order, distance, etc?

> Does summing (or another simple operation) really benefits from multithreading? I thought they are really memory-access-limited.

Maybe. If the cpu is waiting for x.a to arrive it could simultaneously work on x.b.

**Comment by jariji** [comment]
It'll be different if it's a tree vs a memory-contiguous array but

```jl
julia> @btime sum(xs) setup=(xs=rand(10^6));
  107.745 μs (0 allocations: 0 bytes)

julia> @btime ThreadsX.sum(xs) setup=(xs=rand(10^6));
  223.014 μs (890 allocations: 71.45 KiB)
```

**Comment by jariji** [comment]
If we have `(10, 20)` and then `setall` replaces each one with a new container so that we have `(((10,), (100, )), ((20,), (200))`, then there are more nodes than before. 

Are we guaranteed breadth-first traversal?

**Comment by jariji** [comment]
I'm now not sure what I meant.
