### ISSUE TITLE
Q: moving `setindex` to ConstructionBase.jl?

### ISSUE THREAD

**Issue by exaexa** [JuliaObjects/Accessors.jl#152]
For minimality reasons, would it be feasible to move `setindex` to ConstructionBase.jl?

I thought the purpose of the other package is to have a minimal dependency footprint for data structures that want to "support" the Accessors-style access, so I was kinda surprised to see that overloading `setindex` requires whole Accessors.

Is there any reason to have it directly in Accessors?

Thanks for any info :)

**Comment by exaexa** [comment]
cc @stelmo

**Comment by exaexa** [comment]
Ahhhh okay I got confused by this not getting exported from `Base` by default. Fixes the issue, thanks!

**Comment by jw3126** [comment]
yeah `Accessors.setindex` is mostly a hack for addressing some of the limitations of `Base.setindex`. Ideally `Base.setindex` would not have these issues and `Accessors.setindex` would not exist.

**Comment by exaexa** [comment]
@jw3126 OK but if I get it right, overloading the Base one will be sufficient, because the one from Accessors fallbacks just right?

(also just checking: If I implement AbstractDict for my type, I'd have to implement the Accessors.setindex to dispatch properly, right?)

**Comment by jw3126** [comment]
Yeah that sounds right.

**Comment by exaexa** [comment]
ok good thanks a lot!
