### ISSUE TITLE
@set and others fail with Ref dereferencing.

### ISSUE THREAD

**Issue by balenamiaa** [JuliaObjects/Accessors.jl#21]
```
struct A
    a::Int64
end

val = Ref(A(10))

@set val[].a = 30
#=expands to -
begin
    lens = @optic _[].a
    Accessors.set(val, lens, 30)
end
=#
```
which fails with `ERROR: MethodError: no method matching setindex(::Base.RefValue{A}, ::A)`. I suppose you can't define such method because that's type piracy and there's no way to setindex for a Ref without allocating a new one or updating the previous one. Even then, you won't be able to do `val[] = @set val[].a = 30`, which is more natural, but rather have to do `val = @set val[].a = 30`.

I don't know if this should be considered an issue since this only applies to Ref I think, and I don't see a good way around it.

If the macro expanding into the following valid code(only for Ref) doesn't cause an issue:
```
begin
    lens = @optic _.a
    Accessors.set(val[], lens, 30)
end
```
then perhaps there can be a customized variant `@set` for Ref and an overloaded `Accessors.set`.

Or `optic = ($optictransform)($optic)` => `optic = METHOD($optictransform, $optic)` where METHOD specializes on Ref and an overloaded `Accessors.set` so there's no need for a variant `@set`.

All of the above applies to `modify` too, but I am not sure.

**Comment by jw3126** [comment]
Thanks for reporting. This can easily be fixed, we maintain our own [setindex](https://github.com/JuliaObjects/Accessors.jl/blob/master/src/setindex.jl),which is a thin "patched" wrapper around `Base.setindex`. A PR that supports `Ref` would be very welcome!
