### ISSUE TITLE
`ConstructionBase.constructorof` drops parametric type.

### ISSUE THREAD

**Issue by AIxer** [JuliaObjects/Accessors.jl#32]
```julia_repl
julia> a = @set a.octime = 5
ERROR: MethodError: no method matching Implication(::StaticArrays.SVector{2, Word}, ::Int64)
Stacktrace:
 [1] setproperties_object(obj::Implication{Forward}, patch::NamedTuple{(:octime,), Tuple{Int64}})
   @ ConstructionBase mypath\.julia\packages\ConstructionBase\N3vfl\src\ConstructionBase.jl:149
```
my struct definition:
```julia
struct Implication{O} <: Term
    comps::SVector{N, T} where {N, T <: Term}
    octime::UInt
end
```
`ConstructionBase.jl` uses a function called `constructorof`, when it try to find `obj`'s constructor, it use `nameof`, thus it droped my parametric type. 
```julia_repl
julia> typeof(a)
Implication{Forward}

julia> nameof(typeof(a))
:Implication
```

**Comment by rafaqz** [comment]
You need to define your own method of `ConstructionBase.constructorof` for `Implication` because the parameters are not known from the fields. The problem is it can be difficult to detect which parameters should be kept - consider a much more complicated type with nested parameters.

For these simple types we could possibly detect that `O` isnt known from the fields, and keep it.

`Implication` also isnt type-stable by the way, the `SVector` could be a type parameter.

**Comment by AIxer** [comment]
> You need to define your own method of `ConstructionBase.constructorof` for `Implication` because the parameters are not known from the fields. The problem is it can be difficult to detect which parameters should be kept - consider a much more complicated type with nested parameters.
> 
> For these simple types we could possibly detect that `O` isnt known from the fields, and keep it.
> 
> `Implication` also isnt type-stable by the way, the `SVector` could be a type parameter.

Thanks!  I'm gonna make it mutable. 😄

**Comment by rafaqz** [comment]
Why make it mutable? that's not really a good solution to your problem.

**Comment by jw3126** [comment]
@AIxer if overloading `ConstructionBase.constructorof` sounds scary to you, it is just a single line:
```julia
ConstructionBase.constructorof(::Type{Implication{O}}) where {O} = Implication{O}
```

**Comment by rafaqz** [comment]
Hah beat me too it, I had just written the identical code... but yes do that

**Comment by AIxer** [comment]
In fact, I seldom use immutable struct, but I'd very like to use it, maybe I should learn some Haskell. 
I'm rewriting Non-Axiomatic Reasoning System. The term `Implication` is from its formal language called `Narsese`. There are may terms in Narsese, such as `Inheritance`, `Similarity`, etc. they are types of `Term` and use `Term`s as their comps. The whole system never changes its terms in place, but copy then change sometimes (all operation could use immutable methods). emm, the problem is I don't know what's the best structure to represent `Term`, they are can't type stable. Also, I defined `abstract type Term end`. 
So, just simply:
```julia
mutable struct Implication{O <: TemporalOrder} <: Term
    comps::Vector{T} where T <: Term
    octime::UInt
end

struct ExtSet <: Term
    comps::Vector{T} where T <: Term
end
```
emm, any ideas?  And I'm very appreciate your help!  @rafaqz @jw3126

**Comment by rafaqz** [comment]
Always use type parameters. `Vetcor{T}` is not type stable. You can include that limitation with the type parameter as in the first example, but I normally wouldn't bother, and just keep it simple as in the second example.

```julia
 struct Implication{O <: TemporalOrder,C<{Vector{<:Term}}} <: Term
    comps::C
    octime::UInt
end

struct ExtSet{C} <: Term
    comps::C
end
```

**Comment by AIxer** [comment]
Thx! I'm really learned a lot from you! ❤️

**Comment by jw3126** [comment]
@AIxer feel free to reopen, if you still have questions.
