### ISSUE TITLE
Consider subtyping `Function`

### ISSUE THREAD

**Issue by andyferris** [JuliaObjects/Accessors.jl#37]
Hi,

One thing that can help with compatibility elsewhere is to hint your lenses and so-on are functions, by directly subtyping `Function`.

For example the code at https://github.com/JuliaObjects/Accessors.jl/blob/master/src/optics.jl#L345 could become:

```julia
struct PropertyLens{fieldname} <: Function
end 
```

This came up in SplitApplyCombine, which (unfortunately) is currently using `Base.Callable` in a few cases (although I wish the API were factored so it were obvious which terms must be functions rather than collections), [here](https://github.com/JuliaData/SplitApplyCombine.jl/pull/39).

CC @aplavin

**Comment by tkf** [comment]
FWIW I think the main downside of subtyping `Function` is that the compiler de-optimizes a higher-order function that does not call the argument. (Though I really wish it stops doing this...)

IMHO an API that dispatches on `Callable` or `Function` is an anti-pattern and, ideally, should be refactored, as in https://github.com/JuliaLang/julia/pull/34296

**Comment by andyferris** [comment]
> is that the compiler de-optimizes a higher-order function that does not call the argument

Really? That's weird.

> IMHO an API that dispatches on Callable or Function is an anti-pattern and, ideally, should be refactored, as in JuliaLang/julia#34296

You're probably right on that one.

**Comment by tkf** [comment]
I was referring to this issue https://github.com/JuliaLang/julia/issues/33978

**Comment by andyferris** [comment]
I see - I can think of it working like `::Type{T}` then. At least now I know - thanks!

When I opened this issue I didn't see any possible downsides but it's more complex than I imagined, so I'll close this one.

**Comment by aplavin** [comment]
> FWIW I think the main downside of subtyping Function is that the compiler de-optimizes a higher-order function that does not call the argument.

Does this behavior differ depending on whether the passed callable is a `Function` or not?

**Comment by jw3126** [comment]
> 
> Does this behavior differ depending on whether the passed callable is a `Function` or not?

Types also get deoptimized unless you do `f(::Type{T},...)`
