### ISSUE TITLE
expose API to build lenses

### ISSUE THREAD

**Issue by tpapp** [JuliaObjects/Accessors.jl#47]
Setfield.jl allowed interpolation with `$`, but that of course has some corner cases so I understand why it is not allowed in `@optic`. However, it would be nice to be able to build lenses with functions, eg for a

```julia
(a = 1:2, b = 1:3)
```
build the equivalent of `[@optic(_.a[1]), @optic(_.a[2]), @optic(_.b[1]), @optic(_.b[2]), @optic(_.b[3])]` with a loop or similar, eg with a syntax like `Property(:a) ∘ Index(1)` etc.

**Comment by jw3126** [comment]
You can do:
```julia
using Accessors: IndexLens, PropertyLens
PropertyLens{:a}() ∘ IndexLens((1,))
```
Is this what you are looking for? We could add `PropertyLens(:a)` as public API to make it easier to construct property lenses with dynamically known symbol. For index lenses I believe dynamic situations are covered by the macro and I don't know a reason to use `IndexLens` directly.
```julia

julia> inds = (1,2,)
(1, 2)

julia> @optic _[inds...]
(@optic _[1, 2])
```
Does this help or are you looking for something different?

**Comment by aplavin** [comment]
> PropertyLens{:a}() ∘ IndexLens((1,))

The order should be reversed, by the way:

`IndexLens((1,)) ∘ PropertyLens{:a}()`
or
`@optic(_[1]) ∘ @optic(_.a)`

> build the equivalent of [@optic(_.a[1]), @optic(_.a[2]), @optic(_.b[1]), @optic(_.b[2]), @optic(_.b[3])] with a loop or similar

You can already do that:
```julia
julia> [@optic(_[i]) ∘ fopt
        for (fopt, n) in [(optic(_.a), 2), (@optic(_.b), 3)]
        for i in 1:n]
5-element Vector{ComposedFunction{IndexLens{Tuple{Int64}}}}:
 (@optic _[1]) ∘ (@optic _.a)
 (@optic _[2]) ∘ (@optic _.a)
 (@optic _[1]) ∘ (@optic _.b)
 (@optic _[2]) ∘ (@optic _.b)
 (@optic _[3]) ∘ (@optic _.b)


```

**Comment by tpapp** [comment]
Thanks for all the answers. It seems that the functionality is available, I would just suggest the following:

1. export `PropertyLens` and `IndexLens`

2. add sugar `PropertyLens(S::Symbol) = PropertyLens{S}()`, relying on constant prop, and also `IndexLens(i::Int) = IndexLens((i, ))`

3. add a section to the manual documenting lens construction without macros, emphasizing `⨟` (I understand it is in the manual, but easy to miss)

> I don't know a reason to use IndexLens directly

I feel more comfortable with direct construction in some contexts, because I have run into interpolation issues with some macros (not `@optic`, which is written nicely).

**Comment by jw3126** [comment]
These are good ideas @tpapp ! If you make a PR I would be happy to merge it!
