### ISSUE TITLE
Still experimental?

### ISSUE THREAD

**Issue by aplavin** [JuliaObjects/Accessors.jl#59]
I wonder, does this line in README from 2 years ago still holds true?
https://github.com/JuliaObjects/Accessors.jl/blob/2c7fbd14e73ff34509a7b29384b5f3c3353bc607/README.md?plain=1#L12
As I understand, functionality that is not explicitly marked "experimental" is quite stable, and extensive tests ensure that nothing breaks randomly.

**Comment by ztangent** [comment]
Noticed this PR because I just discovered this package! Thought you might want to know that the docs still say the code is experimental:
https://juliaobjects.github.io/Accessors.jl/v0.1.14/#Warning
