### ISSUE TITLE
AccessorsExtra.jl

### ISSUE THREAD

**Issue by aplavin** [JuliaObjects/Accessors.jl#72]
Hi! Wanted to share that I've registered `AccessorsExtra.jl` focusing on integrations of Accessors with other packages: StructArrays, AxisKeys, IntervalSets, and more. It also defines a couple of more opinionated lenses.

[Docs & examples](https://aplavin.github.io/AccessorsExtra.jl/test/notebook.html) (non-exhaustive) | [Source code](https://gitlab.com/aplavin/AccessorsExtra.jl/-/blob/master/src/AccessorsExtra.jl) (with a healthy dose of 🏴‍☠️)

**Comment by jw3126** [comment]
Nice feel free to link it from the Accessors.jl README.
