### ISSUE TITLE
"Concat lens": combine multiple lenses side by side

### ISSUE THREAD

**Issue by aplavin** [JuliaObjects/Accessors.jl#82]
Suppose I have a structure `obj = (flux=10., size=1., coords=(NaN, 5.))` and want to modify (get/set/optimize/...) its flux and the first coordinate.

Would be nice to have something like
```julia
julia> o = concatenate(@optic(_.flux), @optic(first(_.coords)))
ConcatLens((@optic(_.flux), @optic(first(_.coords))))

julia> modify(x -> isnan(x) ? zero(x) : x, obj, o)
(flux=10., size=1., coords=(0., 5.))

julia> getall(obj, o)
(10., NaN)

julia> setall(obj, o, (2., 3.))
(flux=2., size=1., coords=(3., 5.))
```

Currently, it's much less clean and composable - eg `modify`:
```julia
julia> func = x -> isnan(x) ? zero(x) : x
julia> obj = modify(func, obj, @optic(_.flux))
julia> obj = modify(func, obj, @optic(first(_.coords)))
```

I'm not sure about the best name, syntax, and semantics for this operation, though. Comments and suggestions are welcome!
@jw3126 @tkf @rafaqz

**Comment by jw3126** [comment]
I think if you have two "commuting" lenses then you can concatenate them and get a lens again. 
By orthogonal I mean that the following holds:
```julia
lens1(obj) == lens1(@set lens2(obj) = val2))
lens2(obj) == lens2(@set lens1(obj) = val1))
```
So for instance `@optic _.a` and `@optic _.b` are orthogonal (unless you have weird overloads), while 
`@optic _[1:2]` and `@optic _[2:3]` are not.

```julia
struct ConcatLens{L1,L2}
    lens1::L1
    lens2::L2
end
function (lens::ConcatLens)(obj) 
    (lens.lens1(obj), lens.lens2(obj))
end
function set(obj, l::ConcatLens, (val1, val2))
    obj1 = set(obj, l.lens1, val1)
    set(obj1, l.lens2, val2)
end
function concatenate(lens1, lens2) 
    ConcatLens(lens1, lens2)
end
```
There are all kinds of fancy optimizations one could do for instance when concatenating property lenses.

You could also make concatenation of arbitrary optics possible in a similar way, by overloading `modify, setall, getall`. 
I think it is only a sane operation for optics that are commuting in the sense that
```julia
getall(obj, optic1) == getall(setall(obj, optic2, vals2), optic1)
getall(obj, optic2) == getall(setall(obj, optic1, vals1), optic2)
```
We don't want to check that at runtime, it would be the user's responsibility.
Syntax can be improved later on. But a recurrent request is to do ["batch mode" `@set`](https://github.com/JuliaObjects/Accessors.jl/issues/15).

**Comment by jw3126** [comment]
> I may attempt implementing concatlens soon. Is "concat" the right term here?

I think in haskell it is called [productLens](https://github.com/ekmett/lens/blob/479966809048787402adb0ff4d03525b8a65ada6/src/Control/Lens/Unsound.hs#L41-#L61).

**Comment by jw3126** [comment]
Yup I agree. There is also 'alongside' in Haskell, which does what I would intuitively have called product.
