### ISSUE TITLE
Assemble an object from optics

### ISSUE THREAD

**Issue by aplavin** [JuliaObjects/Accessors.jl#83]
It would often be useful, convenient, and general to create an object from values of several optics that uniquely define it, Here, I call this operation "assemble", and below are a couple of motivating examples.
These examples showcase non-trivial conversions, but even trivial ones can be potentially convenient.

For now, this is an RFC: I'm not sure what the best interface would look like from the syntax and implementation PoVs. But would be glad to hear your ideas and suggestions, maybe something similar exists in other ecosystems? I couldn't find anywhere...

Complex from polar:
```julia
@assemble ComplexF64
    abs(_) = 5
    angle(_) = π/3
```

Singleton collection from its only element:
```julia
@assemble Vector  only(_) = 123
@assemble Set  only(_) = 123
@assemble Tuple  only(_) = 123
...
```

Composability:
```julia
@assemble NamedTuple
    @assemble _.x::Complex  abs(_) = 5, angle(_) = π/3
    @assemble _.y::Vector  only(_) = 123
```

Custom structs:
```julia
struct RelativisticVelocity
    β
end

β(v::RelativisticVelocity) = ...
doppler(v::RelativisticVelocity) = ...
lorenz(v::RelativisticVelocity) = ...

@assemble RelativisticVelocity  lorenz(_) = 10
```

```julia
struct Gaussian
    A
    σ
end
A(g::Gaussian) = ...
σ(g::Gaussian) = ...
fwhm(g::Gaussian) = ...
area(g::Gaussian) = ...

@assemble Gaussian  A(_) = 1, fwhm(_) = 1
@assemble Gaussian  A(_) = 1, area(_) = 1
```

**Comment by jw3126** [comment]
One way to implement something like this would be as follows:
```julia
example(::Type{<:Complex}) = 0 + 0im
example(::Type{<:Gaussian}) = ...
```
and then `@assemble Gaussian  A(_) = 1, fwhm(_) = 1` will expand to 
```julia
obj = example(Gaussian)
obj = @set A(obj) = 1
obj = @set fwhm(obj) = 1
```
The disadvantages of this approach would be that it is tricky to make it work for `Vector, Tuple, Set...`. Also
it is only a sane operation, if alle the specified lenses commute and give a complete description of an object.
Performance might also be bad in some cases.
Advantages would be that it works for any lenses and any combination of lenses.

**Comment by jw3126** [comment]
I think a good alternative would be to just define some constructors using say [KeywordDispatch.jl](https://github.com/simonbyrne/KeywordDispatch.jl).
I think the composability of lenses is not very useful here, so keywords are a simpler solution I would personally prefer
```julia
@kwdispatch Gaussian()
@kwmethod f(;A, area) = ...
@kwmethod f(;A, fwhm) = ...
```
Although this does not work well with types you don't own like `Complex` and

**Comment by jw3126** [comment]
Thanks a lot for the update!
