### ISSUE TITLE
IndexLens and changing the container size

### ISSUE THREAD

**Issue by aplavin** [JuliaObjects/Accessors.jl#99]
IndexLens is pretty convenient, and works nicely with index ranges:
```julia
julia> v = [1, 2, 3]

julia> @modify(cumsum, v[2:3])
3-element Vector{Int64}:
 1
 2
 5
```
But the limitation is that the result needs to have the same size:
```julia
julia> @modify(diff, v[2:3])
ERROR: DimensionMismatch: tried to assign 1 elements to 2 destinations
# want [1, 1]

julia> str = "ab cd ef"
julia> @modify(s -> "[$s]", str[4:5])
# want "ab [cd] ef"
```
Fixed replacement length totally makes sense by default, but sometimes resizing is also useful.

I wonder if you have any thoughts on what a reasonable interface for this may look like. Something like `@optic v[FlexIndex(2:3)]` is possible, but IMO reads kinda weird.

**Comment by jw3126** [comment]
Good question. Personally, I encounter this issue so rarely, that I am happy to solve it ad hoc manually.
